server:
  port: 8083
spring:
  application:
    name: pure-client
  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            client-id: oauth2-client-credentials
            client-secret: StGXk1k7Dc0C5pH14JG1y87w07qa39Bh
            authorization-grant-type: client_credentials
            scope:
              - openid
        provider:
          keycloak-client:
            token-uri: http://localhost:8085/realms/oauth2/protocol/openid-connect/token

resource:
  server:
    url: http://localhost:8082


#    @Bean
#    public ClientRegistrationRepository clientRegistrationRepository() {
#    return new InMemoryClientRegistrationRepository(
#    ClientRegistration.withRegistrationId("keycloak")
#    .clientId("your-client-id")
#    .clientSecret("your-client-secret")
#    .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
#    .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
#    .scope("openid", "profile", "email")
#    .authorizationUri("http://localhost:8085/realms/oauth2/protocol/openid-connect/auth")
#    .tokenUri("http://localhost:8085/realms/oauth2/protocol/openid-connect/token")
#    .userInfoUri("http://localhost:8085/realms/oauth2/protocol/openid-connect/userinfo")
#    .jwkSetUri("http://localhost:8085/realms/oauth2/protocol/openid-connect/certs")
#    .issuerUri("http://localhost:8085/realms/oauth2")
#    .userNameAttributeName("sub")
#    .build()
#    );
#}