server:
  port: 8081

spring:
  application:
    name: oauth-client-with-resource-server

  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            client-id: oauth2-client-credentials
            client-secret: StGXk1k7Dc0C5pH14JG1y87w07qa39Bh
            authorization-grant-type: client_credentials
            scope:
              - openid
        provider:
          keycloak-client:
            token-uri: http://localhost:8085/realms/oauth2/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/oauth2

resource:
  server:
    url: http://localhost:8082